### ISSUE TITLE
Adding toolbar in all the fragments

### ISSUE THREAD

**Issue by SamuelBismuth** [SamuelBismuth/Betitarev#2]
Yishay and Joni, please add the toolbar in the fragment you're in charge:

  <Toolbar
        android:id="@+id/toolbar"
        android:title="@string/title_place_bet"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        android:popupTheme="@style/AppTheme.PopupOverlay"
        tools:targetApi="lollipop">
    </Toolbar>
    
Of course, change the title name as it need to be :)

**Comment by yoshago** [comment]
Dear samuel,
do you mean the upper toolbar?
If yes, does it implemented, pushed and merged into master branch already?
sincerely yours, Jonato.

**Comment by SamuelBismuth** [comment]
Dear Jonato, 
Yes, this is what I mean. I just saw that the code I add in the previous issue is not displayed, so I try to ressend the code: 
```
<EditText
        android:id="@+id/bet_phrase"
        android:layout_width="match_parent"
        android:layout_height="100dp"
        android:hint="@string/bet_phrase"
        android:inputType="text">
 </EditText>
```
It should be implemented in all the separate fragment. Maybe in the profile fragment there is no need to implement it.
Peace, 
Best wishes, 
Best regards, 
By order of the Peacky ******* Blinders
Samito.

**Comment by SamuelBismuth** [comment]
fixed
