### ISSUE TITLE
Navigation bar issue

### ISSUE THREAD

**Issue by SamuelBismuth** [SamuelBismuth/Betitarev#3]
The navigation bar has the next problem: When the keyboard is opened, the navigation up with the keyboard, need to fix it.

**Comment by yoshago** [comment]
which fragment/activity are you talking about?

**Comment by SamuelBismuth** [comment]
All off the fragment with edit text or keyboard input

**Comment by SamuelBismuth** [comment]
fixed by @yoshago  thanks
